/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "platform_types.h"
//Base addresses
#define RCC_BASE 0x40021000
#define GPIOA_BASE 0x40010800
//Absolute addresses
#define RCC_APB2ENR		*(vuint32_t *)(RCC_BASE + 0x18)
#define GPIOA_CRH		*(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR		*(vuint32_t *)(GPIOA_BASE + 0x0C)
//Pin Locations
#define RCC_IOPAEN 2
#define GPIOA_PIN13 13

typedef union{
	vuint32_t all_fields;
	struct{
		vuint32_t reserved:13;
		vuint32_t PIN13: 1;
	} Pin;
}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)&GPIOA_ODR;

int main(void)
{
    RCC_APB2ENR |= (1 << RCC_IOPAEN);
	GPIOA_CRH &= 0xff0fffff; //clear bits 20-23 1st before writing on them
	GPIOA_CRH |= 0x00200000; //write 2 on bits 20-23
		for(;;){
		GPIOA_ODR |= (1 << 13);
		for(int i = 0; i < 5000; i++);
		GPIOA_ODR &=~(1 << 13);
		for(int i = 0; i < 5000; i++);
	}
}
